/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.numberToWords;

import org.apache.commons.lang3.StringUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class NumberToWordsIDTest {
    NumberToWordsID classUnderTest = new NumberToWordsID();

    @Test
    void convertToWordsTestFailed() {
        Assertions.assertEquals(classUnderTest.convertNumberToWords(-1L), StringUtils.EMPTY);
    }
}
