/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("org.sonarqube") version "4.4.1.3373"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")
    implementation("com.google.guava:guava:32.1.2-jre")
    implementation("org.apache.commons:commons-lang3:3.12.0")
}

sonarqube {
    properties {
        property("sonar.projectKey", "kennyrobert88_NumberToWords")
        property("sonar.organization", "krobert888")
        property("sonar.host.url", "https://sonarcloud.io")

        // Optional but recommended: use environment variable for security
        System.getenv("SONAR_TOKEN")?.let {
            property("sonar.login", it)
        }
    }
}

testing {
    suites.named<JvmTestSuite>("test") {
        useJUnitJupiter("5.10.3")
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
