/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.numberToWords;

import org.apache.commons.lang3.StringUtils;

public class NumberToWordsID implements NumberToWordsIDImpl {

    @Override
    public String convertNumberToWords(long number) {
        if (this.parameterConstraintChecker(number)) {

        }
        return StringUtils.EMPTY;
    }

    /***
     * helper function for checking constraint in number
     * @param number
     * @return boolean of value in constraint
     ***/
    private boolean parameterConstraintChecker(long number) {
        return number >= Constants.MIN_VALUE && number <= Constants.MAX_VALUE;
    }

    /***
     *
     ***/
    private String helperConvertNumberToWords() {
        return StringUtils.EMPTY;
    }
}
